### ISSUE TITLE
[Question] For testing, override rules and restore previous rules

### ISSUE THREAD

**Issue by ernsheong** [di-ninja/di-ninja#2]
In unit tests, I wish to override some rules. This already works as per below:

> Dependencies definition can be overrided, the last call of addRule or @di decorator will take precedence.

In testing cleanup, I wish to restore the previous rules so that other tests are not affected. Is there a way to restore previous rules? Or at least retrieve a snapshot of the rules at a certain point so that I can restore them again manually later?

**Comment by ernsheong** [comment]
So I guess the DIY way is something like:

```
const rules = {...};

di.addRules(rules);

di.resetRules = function() {
  di.addRules(rules);
};
```

**Comment by takion** [comment]
You can do this way, but you have to disable the [ruleCache](https://github.com/di-ninja/di-ninja#518-rulecache) first
```js
di.config('ruleCache', false)
```
ruleCache is enabled by default for optimization because the main expected usage is only one main call to addRules by application and the processing of rules is the main computing cost of Di-Ninja.

There is another point, the rules are apllied in cascade in a deep merging process (a little like CSS), and in your first call to `di.addRules`, the override will be on [rulesDefault](https://github.com/di-ninja/di-ninja#52-rulesdefault), and on the second call, from the other rules that you have defined, there will be no difference if you explicit all options of a rule but else this can lead to unexpected results.

A workaround is to completely override the rules object like this
```js
di.resetRules = function() {
  di.rules = {} // hard reset
  di.addRules(rules)
}
```
it's a bit hacky and if you call `resetRules` when there is some async rule procressing, you'll make a knot bag.

Another approach would be to explicit all options of a rule on reset
```js
di.resetRules = function() {
  const explicitRules = {}

  Object.keys(rules).forEach(key=>{
    const explicitRule = {}
    di.mergeRule(explicitRule, di.rulesDefault)
    di.mergeRule(explicitRule, rules[key])
    explicitRules[key] = explicitRule
  })

  di.addRules(explicitRules)
}
```

But I think the better way is to instantiate another di container, after all, this is not a damn singleton ;), so you can just
```js
import container from 'di-ninja'

const di = container({
  rules,
})
/*
exactly the same as
const di = container()
di.addRules(rules)
*/

const di2 = container({
  rules2,
})
```

**Comment by ernsheong** [comment]
The separate di container seems the most promising. Thanks for the tip!

Other than that, the caching behavior seems like a gotcha. But not undocumented :)
